# Copyright 2023 RobustMQ Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: [ --allow-multiple-documents ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: proto-fmt-auto
        name: proto fmt auto
        description: Format files with buf automatically.
        entry: bash -c 'buf format -w'
        language: system
        files: \.rs$
        args: [ ]
      - id: hawkeye-fmt-auto
        name: hawkeye fmt auto
        description: Format files with hawkeye automatically.
        entry: bash -c 'hawkeye format'
        language: system
        pass_filenames: true
        files: \.*$
        args: [ ]
      - id: typos
        name: typos
        description: check typo
        entry: bash -c 'typos'
        language: system
        files: \.*$
        pass_filenames: false
      - id: hawkeye-fmt-check
        stages:
          - pre-push
        name: hawkeye fmt check
        description: Check files with hawkeye.
        entry: bash -c 'hawkeye check'
        language: rust
        files: \.*$
        args: [ ]
